version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:asmarafique@db:5432/template_database # Change this line to match your credentials and database name

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres # Replace with your actual PostgreSQL user
      POSTGRES_PASSWORD: asmarafique # Replace with your actual PostgreSQL password
      POSTGRES_DB: template_database # Replace with your actual PostgreSQL database name
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
